names:
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- '16'
- '17'
- '18'
nc: 19
train: /kaggle/input/construction-site-data/DataCombinedWithConstruction/train
val: /kaggle/input/construction-site-data/DataCombinedWithConstruction/val
